// Bundle briefings from the local pipeline library into the app, so a fresh
// install (TestFlight, web, a clone) opens with real briefings instead of an
// empty feed — no server needed to watch them.
//
//   node scripts/make-starter.mjs "Meta Connect 2026" "Apple OpenAI" …
//
// Picks the named briefings (by label, newest match wins) from
// server/data/jobs.json, in the order given, copies their generated clips
// into assets/starter/, and writes src/data/starter.js. With no names, it
// uses STARTER below. Re-run whenever you make briefings worth shipping.
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs';
import path from 'node:path';

const STARTER = ['Meta Connect 2026', 'Apple OpenAI', 'El Niño', 'Gas Prices'];
const names = process.argv.slice(2).length ? process.argv.slice(2) : STARTER;

const DATA = 'server/data';
const OUT_MEDIA = 'assets/starter';
const OUT_JS = 'src/data/starter.js';

const jobs = JSON.parse(readFileSync(path.join(DATA, 'jobs.json'), 'utf8'));
const picked = names.map((name) => {
  const job = jobs
    .filter((j) => j.label === name && j.status === 'ready' && j.mode === 'new')
    .sort((a, b) => b.created_at.localeCompare(a.created_at))[0];
  if (!job) throw new Error(`No ready briefing labelled "${name}" in ${DATA}/jobs.json`);
  return job;
});

rmSync(OUT_MEDIA, { recursive: true, force: true });
mkdirSync(OUT_MEDIA, { recursive: true });

const media = [];
const slim = picked.map((job) => {
  const beats = job.beats
    .filter((b) => b.status === 'ready')
    .map((b) => {
      const { visual_prompt, generation_reason, facts, ...keep } = b;
      if (!b.video_url) return keep;
      const file = path.basename(b.video_url);
      const src = path.join(DATA, 'media', file);
      if (!existsSync(src)) throw new Error(`Missing clip ${src} for "${job.label}"`);
      copyFileSync(src, path.join(OUT_MEDIA, file));
      media.push({ url: b.video_url, file });
      return keep;
    });
  return {
    id: job.id,
    status: job.status,
    mode: 'new',
    news_id: job.news_id,
    label: job.label,
    prompt: job.prompt,
    created_at: job.created_at,
    beats,
  };
});

const js = `// Generated by scripts/make-starter.mjs — do not edit by hand.
// The briefings a fresh install opens with: ${names.join(', ')}.
// Clips are bundled from assets/starter/, so they play without a server.

export const STARTER_JOBS = ${JSON.stringify(slim, null, 2)};

export const STARTER_MEDIA = {
${media.map((m) => `  ${JSON.stringify(m.url)}: require('../../assets/starter/${m.file}'),`).join('\n')}
};
`;
writeFileSync(OUT_JS, js);
console.log(`Starter: ${slim.map((j) => `${j.label} (${j.beats.length} cards)`).join(' · ')} — ${media.length} clips bundled`);
